project:
  type: website

website:
  title: "Jacob Hunter"
  description: "This is Jacob Hunter's blog, where R and data science are used to learn, make an impact, and have fun."
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/jwhunter
      - icon: linkedin
        href: https://www.linkedin.com/in/jacob-hunter-5a66ab139/
format:
  html:
    theme: journal
    css: styles.css

editor: visual

